### ISSUE TITLE
代码编辑框提示错误 

### ISSUE THREAD

**Issue by nuan1989** [twgh/xcgui#10]
错误:panic: Failed to find XEditor_SetStyleFunction procedure in xcgui.dll: The specified procedure could not be found.
  
备注:  自带的代码编辑框的demo, 出错.  把 3.3.3的dll复制过来又可以. 是否这个函数被删除了?

![1](https://user-images.githubusercontent.com/43518669/175763510-5d5c28f0-959d-4730-a311-3e59473ca70b.png)

**Comment by twgh** [comment]
原作者在升级代码编辑框(Editer)的这部分api, 只能等原作者恢复此部分api
