### ISSUE TITLE
如何将html和js还有css封装进去

### ISSUE THREAD

**Issue by passerbyo** [twgh/xcgui#11]

**Comment by twgh** [comment]
1. 如何把文件打包进程序：使用embed包。
2. 如何在炫彩窗口上显示html：炫彩官方还没有支持这个功能，可以使用miniblink，他应该可以绑定炫彩窗口来显示html，miniblink在github上有其他人封装的go的版本，但我没有尝试过。或许以后我会封装一个便于和xcgui结合的miniblink版本。

**Comment by nuan1989** [comment]
> 1. 如何把文件打包进程序：使用embed包。
> 2. 如何在炫彩窗口上显示html：炫彩官方还没有支持这个功能，可以使用miniblink，他应该可以绑定炫彩窗口来显示html，miniblink在github上有其他人封装的go的版本，但我没有尝试过。或许以后我会封装一个便于和xcgui结合的miniblink版本。

mb对html5兼容很差, vue的ui库很多都不能正常运行. 建议封装webview2
