### ISSUE TITLE
360报毒，误报？

### ISSUE THREAD

**Issue by AnkoGo123** [twgh/xcgui#13]
![image](https://user-images.githubusercontent.com/84855094/188491921-0bf88793-d5d1-483a-9aeb-6600a2f7a4b3.png)

**Comment by twgh** [comment]
炫彩如果报毒的话应该是dll报毒而不是exe报毒，360应该拦截dll，因为界面库全部实现代码都在dll里，它是C++写的。

而这个exe报毒证明是调用dll的代码报了毒，而这部分都是开源的，go语言版的这个库只是调用dll函数的库，使用的都是go语言核心库提供的方法。

360杀毒我也在用的，他是很怪的，时报时不报的，这份源码我go run的时候报毒，编译出来运行又不报了，看下图：
![1](https://pic.jitudisk.com/public/2022/09/05/54c3999c66ff4.gif)

**Comment by AnkoGo123** [comment]
我发这个不是为了说你的代码有病毒，是为了让你做到尽量不报毒，少用那些不大规范的dll第三方插件，或者是你的源码访问了一些类似病毒才会访问的区域，要么就是你的cpp编译器版本不是官方下载的

**Comment by AnkoGo123** [comment]
总之杀毒软件 会误报，但是这个概率很低，以前写的go代码编译出来的exe也有报毒的时候，但是这个几乎很少出现

**Comment by twgh** [comment]
关于c++的部分, 这个可以反馈给原作者, 如果有什么建议可以加入群聊(2283812)讨论
