### ISSUE TITLE
是否支持无显卡或者核显运行流畅？

### ISSUE THREAD

**Issue by AnkoGo123** [twgh/xcgui#14]
**Bug 描述**
对错误是什么的清晰描述。

**预期行为**
清晰的描述您期望发生的事情。

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。

**系统:**
系统和版本。

**其他**
其他想说的。

**Comment by AnkoGo123** [comment]
electron天生支持cpu虚化的GPU显示，是否支持没有显卡下运行？

**Comment by twgh** [comment]
我问了原作者, 他说是支持的. 如果没独显可以用gdi模式, 就是app.New(false).
如果还有其他问题可以进群2283812咨询群主, 他是炫彩界面库的原作者
