### ISSUE TITLE
需要特定例子/写法的可以在本贴下面留言

### ISSUE THREAD

**Issue by twgh** [twgh/xcgui#16]
很多人可能没有写过GUI类型的软件，或者没有接触过DriectUI类型的界面库，因此我不知道你们的疑惑会在哪里，需要哪方面更深入的例子，我需要根据你们的需求来继续写出更多的例子，以供所有人查看，请畅所欲言。

**Comment by pizixi** [comment]
大佬你好，想实现类似这样的界面，分三块，左右功能菜单，右侧list，右下侧输出实时日志，把例子都看了一遍，但是实现起来还是费劲，请大佬指教，可否写一个类似例子参考参考，谢谢
![image](https://user-images.githubusercontent.com/56673215/193210149-9810b259-d0bc-4579-badd-8d510a0bc095.png)

**Comment by twgh** [comment]
> 

可能你没有使用设计器来做, 用设计器来做的话, 还是好实现的, 你可以先在设计器里自己搞一下试试

**Comment by pizixi** [comment]
> > 
> 
> 可能你没有使用设计器来做, 用设计器来做的话, 还是好实现的, 你可以先在设计器里自己搞一下试试

谢谢，下午看了一下，还有个问题，如果使用炫彩界面设计器  把ui搞出来，数据怎么跟go代码交互，这个有没有视频或者文档参考参考，我看视频里面大部分是讲炫语言，暂时还不准备学那个，感谢

**Comment by twgh** [comment]
> > > 
> > 
> > 
> > 可能你没有使用设计器来做, 用设计器来做的话, 还是好实现的, 你可以先在设计器里自己搞一下试试
> 
> 谢谢，下午看了一下，还有个问题，如果使用炫彩界面设计器 把ui搞出来，数据怎么跟go代码交互，这个有没有视频或者文档参考参考，我看视频里面大部分是讲炫语言，暂时还不准备学那个，感谢

设计器里给组件设置name, 代码里NewXXXByName就获取到组件了
[https://github.com/twgh/xcgui/wiki/1.4](https://github.com/twgh/xcgui/wiki/1.4)

**Comment by pizixi** [comment]
非常感谢，我研究研究

**Comment by pandak1d** [comment]
可不可以写一个界面展开的例子，类似于这个链接里面的25.折叠面板，http://mall.xcgui.com/942.html

**Comment by zyzlj** [comment]
托盘的例子有吗？

**Comment by twgh** [comment]
> 托盘的例子有吗？

[https://github.com/getlantern/systray](https://github.com/getlantern/systray) 参照他的webview_example例子

**Comment by twgh** [comment]
> 

我建议直接看他的代码, 虽然是其他语言的, 但xcgui的api都是一样的, 本库的xc包里包含所有的api. 
我现在确实没什么时间去翻译一些其他语言的例子.

**Comment by twgh** [comment]
> 可不可以写一个界面展开的例子，类似于这个链接里面的25.折叠面板，http://mall.xcgui.com/942.html

我建议直接看他的代码, 虽然是其他语言的, 但xcgui的api都是一样的, 本库的xc包里包含所有的api.
我现在确实没什么时间去翻译一些其他语言的例子.

**Comment by nuan1989** [comment]
多个go func操作炫彩, 会有多线程问题, 大佬有没有什么好的方式.
