### ISSUE TITLE
[BUG] panic: Failed to find XAnima_SetCallBack procedure in xcgui.dll: The specified procedure could not be found.

### ISSUE THREAD

**Issue by sdxstar** [twgh/xcgui#18]
`an := ani.NewAnima(w.Handle, 1)`
`an.Move(100, 500, 0, 1, xcc.Ease_Flag_Linear, false)`
`an.SetCallBack(anCallback)`
`an.Run(w.Handle)`

when i try to set callback for animation, get below panic.

panic: Failed to find XAnima_SetCallBack procedure in xcgui.dll: The specified procedure could not be found.

any help please?

**Comment by twgh** [comment]
Problem within dll, waiting for update

**Comment by sdxstar** [comment]
thanks
