### ISSUE TITLE
[提问] ShapeText文本颜色设置问题

### ISSUE THREAD

**Issue by linzedo** [twgh/xcgui#25]
ShapeText能否部分字样进行颜色处理，因为一段文本有个别字要进行高亮处理

**Comment by linzedo** [comment]
或者能否让ShapeText能识别类似以下的标签包裹效果，实现颜色识别
![企业微信截图_17054595354580](https://github.com/twgh/xcgui/assets/106944736/c5aefa85-b879-4ba5-a152-15aa93a4692d)

**Comment by twgh** [comment]
自己封装一个，把编辑框包装一下。
给编辑框设置禁用焦点，禁用绘制边框和焦点，开启鼠标穿透。
添加多种格式的文本在编辑框的例子里有。
