### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by linzedo** [twgh/xcgui#27]
**Bug 描述**
目前循环调用以下函数一段时间后会触发句柄失效的情况，使用go run或者go build编译成exe文件都会，但是用goland运行程序就不会有这个情况

**预期行为**
清晰的描述您期望发生的事情。
不会报错
**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。
![1705817956702](https://github.com/twgh/xcgui/assets/106944736/a0afb4d5-e139-46e5-8f9d-08fcb6211576)
![image](https://github.com/twgh/xcgui/assets/106944736/7b4583a4-a062-45b7-a3db-e97b02aafef3)
![image](https://github.com/twgh/xcgui/assets/106944736/b1eea3d5-9d5b-480f-988e-d6f7c7330a32)

**系统:**
win11

**其他**
其他想说的。

**Comment by twgh** [comment]
图片加载一次后，可以调用EnableAutoDestroy(false)
