### ISSUE TITLE
[BUG] 有时候启动时卡死在w,show(true) 里面,程序就不动了。

### ISSUE THREAD

**Issue by happychui** [twgh/xcgui#28]
**Bug 描述**
对错误是什么的清晰描述。

**预期行为**
清晰的描述您期望发生的事情。

**截图**
如果可以，请添加屏幕截图以帮助解释您的问题。

**系统:**
系统和版本。

**其他**
其他想说的。

**Comment by twgh** [comment]
init之后到run之前不要进行很耗时的操作, 可以把下面的代码加到run上面
```go
	time.AfterFunc(time.Millisecond*10, func() {
		go func() {
		//一些耗时的操作, 比如从网络获取数据
		}()
	})
```

**Comment by twgh** [comment]
另外注意如果你要在协程里操作ui的话, 使用xc.CallUT(), 在回调里操作ui, 这指的是对ui的一些写的操作和redraw等

**Comment by happychui** [comment]
什么都没做，只添加了几个2个控件

「twgh ***@***.***>」在 2024年4月16日 週二，下午6:36 寫道：

**Comment by happychui** [comment]
程序里面只有两个控件显示

「twgh ***@***.***>」在 2024年4月16日 週二，下午6:40 寫道：

**Comment by happychui** [comment]
多运行几次就有机会卡了

「Roy Chui ***@***.***>」在 2024年4月16日 週二，下午6:41 寫道：

**Comment by happychui** [comment]
> init之后到run之前不要进行很耗时的操作, 可以把下面的代码加到run上面
> 
> ```go
> 	time.AfterFunc(time.Millisecond*10, func() {
> 		go func() {
> 		//一些耗时的操作, 比如从网络获取数据
> 		}()
> 	})
> ```

还没到run, show已经过不去了

**Comment by happychui** [comment]
把这个放到ui初始化前
runtime.LockOSThread()
defer runtime.UnlockOSThread()

这个有效，谢谢

**Comment by nuan1989** [comment]
> 把这个放到ui初始化前 runtime.LockOSThread() defer runtime.UnlockOSThread()
> 
> 这个有效，谢谢

十有八九是多个线程操作ui造成的, 可以看看例子里面
