### ISSUE TITLE
[BUG] bkmanager.setInfo 无法正常工作。

### ISSUE THREAD

**Issue by spooking** [twgh/xcgui#31]
**Bug 描述**
a := app.New(true)
	w := window.NewByLayoutStringW(str, 0, 0)
	w.AdjustLayout()

	bth := a.GetObjectByName("btn1")
	fmt.Println(bth)
	bt1 := widget.NewButtonByHandle(bth)
	fmt.Println(bt1.Handle)
	bmk := bkmanager.NewByHandle(bt1.Handle)
	fmt.Println(bmk.Handle)
	if bmk != nil {
		bmk.SetInfo("{99:1.9.9;98:16(0)32(1)64(2);5:2(15)20(1)21(3)26(1)22(-7839744)23(255)9(5,5,5,5);5:2(15)20(1)21(3)26(1)22(-4094208)23(255)9(5,5,5,5);5:2(15)20(1)21(3)26(1)22(-7839744)23(255)9(5,5,5,5);}")
	} else {
		fmt.Println("Error")
	}

**截图**
![图片](https://github.com/twgh/xcgui/assets/22233730/1812e5b9-64b4-4d97-a61a-38c203dc04e6)

**版本:**
windows 11
golang     1.20.0
xcgui.dll    3.3.9.0

**其他**
是我的写法有问题吗？有没有例子

**Comment by twgh** [comment]
句柄无效是因为你传的是按钮句柄, 得是背景管理器句柄
bmk := bkmanager.NewByHandle(bt1.GetBkManager())

**Comment by spooking** [comment]
感谢🙏

**Comment by twgh** [comment]
直接按钮.SetBkInfo
