### ISSUE TITLE
[提问] 这种键盘监听需要把焦点放在程序窗口上才能监听，有能全局监听的方子吗，就例如全局的快捷键之类的

### ISSUE THREAD

**Issue by linzedo** [twgh/xcgui#32]
![image](https://github.com/twgh/xcgui/assets/106944736/cb65c69e-5465-4202-ad7b-0bb31c78419a)

**Comment by twgh** [comment]
有注册热键的例子

**Comment by linzedo** [comment]
但我看例子里的。没法进行重复注册呀，如果我多开程序的话

**Comment by linzedo** [comment]
![image](https://github.com/twgh/xcgui/assets/106944736/ec32456a-9a2b-42bd-be9f-035fe2218ffd)
还有就是在修改edit文本内容后调用Show方法的时候，窗口都会获取焦点，这种有没有办法避免，就不让窗口因为响应获取焦点

**Comment by twgh** [comment]
> 但我看例子里的。没法进行重复注册呀，如果我多开程序的话

https://github.com/twgh/xcgui-example/blob/main/HookKeyboard/HookKeyboard.go

**Comment by twgh** [comment]
> ![image](https://private-user-images.githubusercontent.com/106944736/346282777-ec32456a-9a2b-42bd-be9f-035fe2218ffd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNDEyNDAsIm5iZiI6MTcyMDM0MDk0MCwicGF0aCI6Ii8xMDY5NDQ3MzYvMzQ2MjgyNzc3LWVjMzI0NTZhLTlhMmItNDJiZC1iZTlmLTAzNWZlMjIxOGZmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwODI5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTUxYTQwYjRkZmQ0MjVmNDIyODE4NWIyZGU0ZGE3MTQ5MjAwZmI2ZTA4ZjNlMDk4OTJkMDZlOGExYWE4OWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kfo2IdLvkIqZMaqBzCvLNH3FL3l3wGffScyMb9vd3n4) 还有就是在修改edit文本内容后调用Show方法的时候，窗口都会获取焦点，这种有没有办法避免，就不让窗口因为响应获取焦点

ShowWindow()有多种方式, Show(true)只是简化写法

**Comment by linzedo** [comment]
这个有办法避免说点击一个选项下拉菜单就会被收起的情况吗

**Comment by linzedo** [comment]
![image](https://github.com/user-attachments/assets/69826888-ca15-400d-9ecc-2a42f3e15c8d)
请问这个有办法避免点一个选项，菜单就会收起的情况吗

**Comment by twgh** [comment]
> ![image](https://private-user-images.githubusercontent.com/106944736/350694852-69826888-ca15-400d-9ecc-2a42f3e15c8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0ODU1MTMsIm5iZiI6MTcyMTQ4NTIxMywicGF0aCI6Ii8xMDY5NDQ3MzYvMzUwNjk0ODUyLTY5ODI2ODg4LWNhMTUtNDAwZC05ZWNjLTJhNDJmM2UxNWM4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxNDIwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWMxYWE1MDYyYjk3ZThhMzY2YTBjNGU0M2U4NTk5OTEwNDJiNGRhMmJkMjU0NzZjZGVlMTkyMmIxNDRlZWZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o-VcCneA-mxL3aK6jQKEPiIsMCPwI9-lwQEQNUfkLq8) 请问这个有办法避免点一个选项，菜单就会收起的情况吗

菜单点了之后是直接销毁掉了的, 你自己创建一个窗口, 里面一竖排的按钮, 也就和菜单一样了, 这是一种常用的方式, 本身自带的菜单满足不了更花里胡哨的需求

**Comment by linzedo** [comment]
Exception 0xc0000005 0x0 0xffffffffffffffff 0x7ffcc7b60e47
PC=0x7ffcc7b60e47

runtime.cgocall(0x55e7a0, 0xc000100408)
	E:/GoLang/Go/go1.22.1/src/runtime/cgocall.go:157 +0x3e fp=0xc000473cd8 sp=0xc000473ca0 pc=0x4e731e
syscall.SyscallN(0x7ffcc7a65d30, {0x0?, 0x0, 0xc0002da900?})
	E:/GoLang/Go/go1.22.1/src/runtime/syscall_windows.go:544 +0x11d fp=0xc000473d60 sp=0xc000473cd8 pc=0x559d5d
syscall.(*Proc).Call(0xc0002c44c0, {0x0, 0x0, 0x0})
	E:/GoLang/Go/go1.22.1/src/syscall/dll_windows.go:166 +0x7e fp=0xc000473df0 sp=0xc000473d60 pc=0x5d019e
syscall.(*LazyProc).Call(0xc0002da900, {0x0, 0x0, 0x0})
	E:/GoLang/Go/go1.22.1/src/syscall/dll_windows.go:286 +0x95 fp=0xc000473e88 sp=0xc000473df0 pc=0x5d0c95
github.com/twgh/xcgui/xc.XRunXCGUI()
	E:/GoLang/GoPath/pkg/mod/github.com/twgh/xcgui@v1.3.391/xc/globalapi.go:22 +0x25 fp=0xc000473eb8 sp=0xc000473e88 pc=0x10ca4c5
github.com/twgh/xcgui/app.(*App).Run(0x1903b60)
	E:/GoLang/GoPath/pkg/mod/github.com/twgh/xcgui@v1.3.391/app/app.go:30 +0x25 fp=0xc000473ed0 sp=0xc000473eb8 pc=0x10e9445
ocr-scan/xcgui.(*xcgui).Run(0xc000108760)
	E:/GoLang/Git_Go_Project/ocr-scan/xcgui/xcgui.go:243 +0x25 fp=0xc000473f10 sp=0xc000473ed0 pc=0x10f79a5
ocr-scan/xcgui.InitXcgui.func1.1()
	E:/GoLang/Git_Go_Project/ocr-scan/xcgui/xcgui.go:94 +0x165 fp=0xc000473fe0 sp=0xc000473f10 pc=0x10f6485
runtime.goexit({})
	E:/GoLang/Go/go1.22.1/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000473fe8 sp=0xc000473fe0 pc=0x55cfc1
created by ocr-scan/xcgui.InitXcgui.func1 in goroutine 1
	E:/GoLang/Git_Go_Project/ocr-scan/xcgui/xcgui.go:81 +0x85

请问这个回收错误是底层的问题吗

**Comment by twgh** [comment]
> Exception 0xc0000005 0x0 0xffffffffffffffff 0x7ffcc7b60e47 PC=0x7ffcc7b60e47
> 
> runtime.cgocall(0x55e7a0, 0xc000100408) E:/GoLang/Go/go1.22.1/src/runtime/cgocall.go:157 +0x3e fp=0xc000473cd8 sp=0xc000473ca0 pc=0x4e731e syscall.SyscallN(0x7ffcc7a65d30, {0x0?, 0x0, 0xc0002da900?}) E:/GoLang/Go/go1.22.1/src/runtime/syscall_windows.go:544 +0x11d fp=0xc000473d60 sp=0xc000473cd8 pc=0x559d5d syscall.(*Proc).Call(0xc0002c44c0, {0x0, 0x0, 0x0}) E:/GoLang/Go/go1.22.1/src/syscall/dll_windows.go:166 +0x7e fp=0xc000473df0 sp=0xc000473d60 pc=0x5d019e syscall.(*LazyProc).Call(0xc0002da900, {0x0, 0x0, 0x0}) E:/GoLang/Go/go1.22.1/src/syscall/dll_windows.go:286 +0x95 fp=0xc000473e88 sp=0xc000473df0 pc=0x5d0c95 [github.com/twgh/xcgui/xc.XRunXCGUI](https://github.com/twgh/xcgui/xc.XRunXCGUI)() E:/GoLang/GoPath/pkg/mod/github.com/twgh/xcgui@v1.3.391/xc/globalapi.go:22 +0x25 fp=0xc000473eb8 sp=0xc000473e88 pc=0x10ca4c5 github.com/twgh/xcgui/app.(*App).Run(0x1903b60) E:/GoLang/GoPath/pkg/mod/github.com/twgh/xcgui@v1.3.391/app/app.go:30 +0x25 fp=0xc000473ed0 sp=0xc000473eb8 pc=0x10e9445 ocr-scan/xcgui.(*xcgui).Run(0xc000108760) E:/GoLang/Git_Go_Project/ocr-scan/xcgui/xcgui.go:243 +0x25 fp=0xc000473f10 sp=0xc000473ed0 pc=0x10f79a5 ocr-scan/xcgui.InitXcgui.func1.1() E:/GoLang/Git_Go_Project/ocr-scan/xcgui/xcgui.go:94 +0x165 fp=0xc000473fe0 sp=0xc000473f10 pc=0x10f6485 runtime.goexit({}) E:/GoLang/Go/go1.22.1/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000473fe8 sp=0xc000473fe0 pc=0x55cfc1 created by ocr-scan/xcgui.InitXcgui.func1 in goroutine 1 E:/GoLang/Git_Go_Project/ocr-scan/xcgui/xcgui.go:81 +0x85
> 
> 请问这个回收错误是底层的问题吗

XRunXCGUI这个是消息循环, 这里报错代表你有不规范的操作, 具体是什么操作我是没办法知道的
