### ISSUE TITLE
[功能请求]  托盘, 建议window.NewTrayIcon() 的子方法, 再封装一个xTrayIcon_Del方法

### ISSUE THREAD

**Issue by nuan1989** [twgh/xcgui#36]
建议在 window.NewTrayIcon() 的子方法中也得加一个删除图标的方法, 这个文件内该有的方法都很齐全了, 唯独删除图标需要访问xc.XTrayIcon_Del 删除. 

或者有没有办法让他关闭窗口后自动删除图标. 

![01](https://github.com/user-attachments/assets/b5a104da-e27f-48cb-addd-0175263b17fd)

**Comment by twgh** [comment]
```go
// Show 托盘图标_显示. 从系统托盘显示或隐藏图标.
//
// isShow: 是否显示. 内部原理如下:
//   - true: 执行 xc.XTrayIcon_Add().
//   - false: 执行 xc.XTrayIcon_Del().
func (t *TrayIcon) Show(isShow bool) *TrayIcon {
	if isShow {
		t.Result = xc.XTrayIcon_Add(t.HWindow, t.Id)
	} else {
		t.Result = xc.XTrayIcon_Del()
	}
	return t
}
```

**Comment by nuan1989** [comment]
> ```go
> // Show 托盘图标_显示. 从系统托盘显示或隐藏图标.
> //
> // isShow: 是否显示. 内部原理如下:
> //   - true: 执行 xc.XTrayIcon_Add().
> //   - false: 执行 xc.XTrayIcon_Del().
> func (t *TrayIcon) Show(isShow bool) *TrayIcon {
> 	if isShow {
> 		t.Result = xc.XTrayIcon_Add(t.HWindow, t.Id)
> 	} else {
> 		t.Result = xc.XTrayIcon_Del()
> 	}
> 	return t
> }
> ```

有道理, 好主意, 直接隐藏就好了, 都不用删除. 谢谢.
