### ISSUE TITLE
Does xcgui also compile for Linux and MacOSX

### ISSUE THREAD

**Issue by lonnietc** [twgh/xcgui#7]
Hello,

I like what I have seen in your Xcgui github site but need something that also compile across platforms for Linux and Mac OSX as well as Windows.

Additionally, I am looking to see if you have any examples that show a type of Spreadsheet and also maybe embedding 3D graphics in a window frame as well.

Any information on any of this would be greatly appreciated.
Thanks

**Comment by twgh** [comment]
I'm not the author of `xcgui.dll`, but I think this probably won't happen, the original author has no idea in this regard.

As for spreadsheets, unfortunately xcgui does not provide support for this, you need to use a third-party library to embed the xcgui window.
